kind: ConfigMap
apiVersion: v1
metadata:
  name: envoy-proxy-details-config
  namespace: default
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8001
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: "ingress"
              access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: "/dev/stdout"
              route_config:
                name: local_route
                virtual_hosts:
                - name: service
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: details_service
              http_filters:
              - name: envoy.filters.http.router
                typed_config: {}
      clusters:
      - name: details_service
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: details_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: details-envoy-service.default.svc.cluster.local
                    port_value: 4000
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081
---
# Service for details
apiVersion: v1
kind: Service
metadata:
  labels:
    app: details
    version: v1
  name: details-envoy-service
  namespace: default
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 8001
  selector:
    app: details
  sessionAffinity: None
  type: ClusterIP
