kind: ConfigMap
apiVersion: v1
metadata:
  name: envoy-proxy-pinger1-config
  namespace: default
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8002
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              access_log:
                - name: envoy.file_access_log
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: "/dev/stdout"
              route_config:
                name: local_route
                virtual_hosts:
                - name: pinger-service1
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: pinger-service1
                  
              http_filters:
              - name: envoy.filters.http.router
                typed_config: {}
      clusters:
      - name: pinger-service1
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: pinger-service1
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: envoy-pinger-v1-service.default.svc.cluster.local
                    port_value: 3000
      
        
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081
---
# Service for frontend-proxy
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: pinger
    version: v1
  name: envoy-pinger-v1-service
  namespace: default
spec:
  ports:
  - name: envoy-web
    port: 3000
    protocol: TCP
    targetPort: 8002
  selector:
    app: pinger
    version: v1
  sessionAffinity: None
  type: ClusterIP